import EulersGem.Faces
import EulersGem.SimplexEuler
import EulersGem.Polyhedron
import EulersGem.Hyperplane
import EulersGem.AffDim
import EulersGem.EulerChar
import EulersGem.CellGeometry
import EulersGem.Polytope
import EulersGem.Cone
import EulersGem.FaceCell
import EulersGem.ConeFaceCell
import EulersGem.EulerPoincare
import EulersGem.ConeSlice
import EulersGem.Embed
import EulersGem.Platonic
import EulersGem.Picks
import EulersGem.LatticeTriangle
import EulersGem.LatticePolygon
import EulersGem.PicksTriangulation
import EulersGem.PlanarTriangulation
import EulersGem.FanDisk
import EulersGem.LatticeFan
import EulersGem.PolytopeFaces
import EulersGem.PlatonicOfEuler
import EulersGem.SimplexFaces
import EulersGem.GeometricPlatonic
